<a href="https://colab.research.google.com/github/fatimaezzahrabakas61-web/meteo_project/blob/main/meteo_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

cration fonction

In [2]:
import pandas as pd

In [4]:
df=pd.read_csv("data.csv")

In [3]:
pwd

'/content'

In [5]:
df.head()

                                                                                                                     OUARZAZATE, MO (MO000060265)
Date       TAVG (Degrees Fahrenheit) TMAX (Degrees Fahrenheit) TMIN (Degrees Fahrenheit) PRCP (Inches) SNOW (Inches)                SNWD (Inches)
1965-09-13 78                        88                        59                        NaN           NaN                                    NaN
1965-09-14 78                        90                        61                        NaN           NaN                                    NaN
1965-09-15 77                        NaN                       61                        NaN           NaN                                    NaN
1965-09-16 79                        90                        63                        NaN           NaN                                    NaN

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("data.csv")
df.head()

                                                                                                                     OUARZAZATE, MO (MO000060265)
Date       TAVG (Degrees Fahrenheit) TMAX (Degrees Fahrenheit) TMIN (Degrees Fahrenheit) PRCP (Inches) SNOW (Inches)                SNWD (Inches)
1965-09-13 78                        88                        59                        NaN           NaN                                    NaN
1965-09-14 78                        90                        61                        NaN           NaN                                    NaN
1965-09-15 77                        NaN                       61                        NaN           NaN                                    NaN
1965-09-16 79                        90                        63                        NaN           NaN                                    NaN

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt